#!/usr/bin/perl
use strict;
use warnings;
use feature qw/say/;
use Date::Calc qw/Today Delta_Days Date_to_Days/;
use File::Basename qw(basename);
my $NAME = basename($0);

if(@ARGV == 1) {
	my ($y,$m,$d) = split /-/, shift;
	if(Date_to_Days(Today) > Date_to_Days($y,$m,$d)) {
		say Delta_Days($y,$m,$d, Today);
	} else {
		say Delta_Days(Today, $y,$m,$d);
	}
} elsif(@ARGV == 2) {
	say Delta_Days((split /-/, shift), (split /-/, shift));
} else {
	say << "EOF";
USAGE:
  $NAME <start date> <end date> # range from start date to end date
  $NAME <end date> # range from today to end date
  $NAME <start date> # range from start date to today
EOF
}

