#!/bin/sh

IP=$( printf $1 | awk -F . '{print $4 "." $3 "." $2 "." $1}' )

echo "[ $1 ]"

dig +short $IP.origin.asn.cymru.com TXT | sed -e 's/"//g' | awk -F \| \
	'{ print "ASN:      " $1
	   print "Block:   "  $2
	   print "Country: "  $3
	   print "RIR:     "  $4
	   print "Date:    "  $5
	   print ""
	 }'

