#!/bin/sh
# Best of class logging facility, inspired by Python's logging framework
log() { echo "$1:" "$@" >&2; }
error() { log ERROR "$@"; }
warn() { log WARN "$@"; }
info() { log INFO "$@"; }

die() { error "$@"; exit 1; }

witch() {
	local name="$1" IFS=: p
	case $name in
		*/*)
			[ -e "$name" ] || return 1
			echo "$name"
			return
			;;
	esac
	for p in $PATH; do
		[ -e "$p/$name" ] && break
	done
	[ -e "$p/$name" ] || return 1
	echo "$p/$name"
}
