#!/usr/bin/python3
# scrape content from web pages using css selectors
#
# e.g.
#
#  $ selector-scrape https://en.wikipedia.org/wiki/List_of_HTTP_status_codes 'dl > dt'
#  100 Continue
#  101 Switching Protocols
#  102 Processing (WebDAV; RFC 2518)
#  103 Early Hints (RFC 8297)
#  200 OK
#  201 Created
#  202 Accepted
#  203 Non-Authoritative Information (since HTTP/1.1)
#  204 No Content
#  ...
#
# Or from stdin:
#
#  $ selector-scrape 'dl > dt' <list_of_http_status_codes.html
#
# You have to figure out the magic selector string yourself. And yeah, don't
# forget to quote it, especially if you're using '>' :-).

import sys
import requests
from bs4 import BeautifulSoup

uri = sys.argv.pop(1) if len(sys.argv) > 2 else None
selector = sys.argv[1]

if uri:
    resp = requests.get(uri)
    resp.raise_for_status()
    blob = resp.content
else:
    blob = sys.stdin

bs = BeautifulSoup(blob, features='lxml')

for r in bs.select(selector):
    print(r.text)
